---
apiVersion: v1
kind: Service
metadata:
  name: ${sas-scr-published-name}-service
  namespace: ${custom-scr-namespace}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ${sas-scr-published-name}
